name: Continuous Integration Pipeline

on:
    pull_request:
        branches: [main]

jobs:
    test_pull_request:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                node-version: 20
            - run: npm ci
            - run: npm run start
            - run: npm run test
            - run: npm run build
 
